### PR TITLE
fix: extraneous linefeeds

### PR DESCRIPTION
**Pull request by Jacco**
This fixes problem of extraneous line feeds in this file. They were introduced in a extra merged conflict commit in #24 

I compared it with the original english version (in the history using blame) and the line-count now matches with the original.

Hopefully we will start receiving sync requests again.

This was the only problem I found in the extra merge commits done.

But we also need to fix all extraneous line feed of the PRs that were merged mentioned in #41

Tasks
- [x] #10 
- [x] #11
- [x] #13
- [x] #16
- [x] #17
- [x] #19
- [x] #20
- [x] #21

### CODE REVIEW

**Comment by Keraito** [comment]
@Jacco lemme know when you have fixed all the PRs. I'll review again and get it merged asap

**Comment by Jacco** [comment]
@Keraito it is done

**Comment by Jacco** [comment]
Still can't do anything here because the circleCI has failed. Checked the site but I can't find this specific run. I'll add a commit to see if circle ci run again.

**Comment by Jacco** [comment]
Accidently squashed it...

**Pull request merged**
